version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    volumes:
      - .:/app
    env_file:
      - .env
